require(TSA)
data("larain")
data("color")
data("hare")
data("tempdub")
data("oilfilters")
data("rwalk")
model1 = lm(rwalk ~ time(rwalk))
summary(model1)
win.graph(width = 4.875,height = 2.5,pointsize = 8)
plot(rwalk,type='o',ylab='y')
abline(model1)

month. = season(tempdub)
model2 = lm(tempdub~month.)
summary(model2)
har. = harmonic(tempdub,1)
model3 = lm(tempdub~har.)

win.graph(width = 4.875,height = 2.5,pointsize = 8)
data("ar1.s")
plot(ar1.s,ylab=expression(Y[t]),type='o')
plot(y=ar1.s,x=zlag(ar1.s),ylab=expression(Y[t]),xlab=expression(Y[t-1]),type='p')