require(RcppDL)
require('ltm')
data(Mobility)
data = Mobility
set.seed(2395)
n=nrow(data)
sample = sample(1:n,1000,FALSE)
data <-as.matrix(Mobility[sample ,])
n=nrow(data)
train <- sample(1:n, 800 , FALSE )
x_train <-matrix(as.numeric(unlist(data[train ,])),nrow=nrow(data[train ,]))
x_test <-matrix(as.numeric(unlist(data[-train ,])),nrow=nrow(data[-train ,]) )
x_train <-x_train[,-c(4 ,6)]
x_test <-x_test[,-c(4 ,6)]
y<-apply(cbind(data[,4],data[,6]),1,max, na.rm = TRUE )
y_train <-as.numeric(y[train])
temp <-ifelse(y_train ==0 , 1, 0)
y_train <-cbind(y_train , temp )
y_test <-as.numeric(y[-train ])
temp1 <-ifelse(y_test ==0 , 1, 0)
y_test <-cbind(y_test , temp1 )
hidden = c(12 ,10)
fit <- Rdbn(x_train , y_train , hidden )
summary( fit )
pretrain(fit)
finetune(fit)

predProb<-predict(fit,x_test)
pred1 <-ifelse(predProb[ ,1] >=0.5 , 1, 0)
table(pred1 ,y_test[ ,1] , dnn =c("Predicted" , "Observed"))